name: Auto Commit
 
# Allows you to run this workflow manually from the Actions tab

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Déclencheur quotidien à minuit

jobs:
  auto_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Créer un fichier au nom aléatoire
        run: echo "Contenu du fichier" > $(uuidgen).txt

      - name: Configurer l'identité Git
        run: |
          git config --global user.email "nathan.millescamps@gmail.com"
          git config --global user.name "NatMilles"

      - name: Faire un commit
        run: |
          git add .
          git commit -m "Auto commit $(date +%F)"
          git push
