# This is a basic workflow to help you get started with Actions


on:
  schedule:
    - cron: '0 0 * * *' # Déclencheur quotidien à minuit

jobs:
  auto_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Configurer l'identité Git
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"

      - name: Faire un commit
        run: |
          git add .
          git commit -m "Auto commit $(date +%F)"
          git push
